<a href="https://colab.research.google.com/github/poojan14/AML-Practicals/blob/master/Practical_8_CCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduced by Harold Hotelling, CCA is a way of inferring information from cross-covariance matrices. Typical use for CCA in the experimental context is to take two sets of variables and see what is common among the two sets. 

In [18]:
!pip install pydrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
 
# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
download = drive.CreateFile({'id':'1bKPBNFvcO5pzfLkinyU7PIkX_jxcEf96'})
download.GetContentFile('NYC_school.csv')

In [0]:
import pandas as pd
df = pd.read_csv('NYC_school.csv')

In [21]:
df.head()

Adjusted Grade  ... Grade 8 Math 4s - Economically Disadvantaged
0            NaN  ...                                            0
1            NaN  ...                                            0
2            NaN  ...                                            0
3            NaN  ...                                            0
4            NaN  ...                                            0

[5 rows x 161 columns]

In [0]:
# choose relevant features
df = df[['Rigorous Instruction %',
      'Collaborative Teachers %',
     'Supportive Environment %',
       'Effective School Leadership %',
   'Strong Family-Community Ties %',
    'Trust %','Average ELA Proficiency',
       'Average Math Proficiency']]
# drop missing values
df = df.dropna()
# separate X and Y groups
X = df[['Rigorous Instruction %',
      'Collaborative Teachers %',
     'Supportive Environment %',
       'Effective School Leadership %',
   'Strong Family-Community Ties %',
    'Trust %'
      ]]
Y = df[['Average ELA Proficiency',
       'Average Math Proficiency']]


In [23]:
for col in X.columns:
    X[col] = X[col].str.strip('%')
    X[col] = X[col].astype('int')
# Standardise the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=True, with_std=True)
X_sc = sc.fit_transform(X)
Y_sc = sc.fit_transform(Y)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [24]:
!pip install pyrcca

**Canonical Correlation**

In [27]:
import rcca

nComponents = 2 # min(p,q) components
cca = rcca.CCA(kernelcca = False, reg = 0., numCC = nComponents,)
# train on data
cca.train([X_sc, Y_sc])
print('Canonical Correlation Per Component Pair:',cca.cancorrs)
print('% Shared Variance:',cca.cancorrs**2)

Training CCA, kernel = None, regularization = 0.0000, 2 components
Canonical Correlation Per Component Pair: [0.46059902 0.18447786]
% Shared Variance: [0.21215146 0.03403208]


**Canonical Weights**

In [28]:
cca.ws


[array([[-0.00375779,  0.0078263 ],
        [ 0.00061439, -0.00357358],
        [-0.02054012, -0.0083491 ],
        [-0.01252477,  0.02976148],
        [ 0.00046503, -0.00905069],
        [ 0.01415084, -0.01264106]]), array([[ 0.00632283,  0.05721601],
        [-0.02606459, -0.05132531]])]

**Canonical Loadings**

In [30]:
import numpy as np

print('Loading for Math Score:',np.corrcoef(cca.comps[0][:,0],Y_sc[:,0])[0,1])
print('Loading for ELA Score:',np.corrcoef(cca.comps[0][:,0],Y_sc[:,1])[0,1])


Loading for Math Score: -0.4106778140971078
Loading for ELA Score: -0.4578120954218724


**Canonical Covariates**

In [31]:
cca.comps[0]


array([[ 0.00521903,  0.01840999],
       [-0.03173083,  0.00669952],
       [ 0.02066659, -0.02319188],
       ...,
       [ 0.00029259,  0.0018127 ],
       [-0.02341333, -0.00532078],
       [ 0.00647899,  0.00178834]])

In [32]:
cca.comps[0][:,0]


array([ 0.00521903, -0.03173083,  0.02066659, ...,  0.00029259,
       -0.02341333,  0.00647899])

In [33]:
cca.comps[0][:,1]


array([ 0.01840999,  0.00669952, -0.02319188, ...,  0.0018127 ,
       -0.00532078,  0.00178834])

In [34]:
cca.comps[1]


array([[ 0.02079591, -0.00760554],
       [-0.01557288, -0.01886755],
       [ 0.00463834, -0.00862955],
       ...,
       [-0.01923392, -0.00883273],
       [-0.03327623, -0.05742338],
       [-0.02529823, -0.02446945]])

In [35]:
cca.comps[1][:,0]


array([ 0.02079591, -0.01557288,  0.00463834, ..., -0.01923392,
       -0.03327623, -0.02529823])

In [36]:
cca.comps[1][:,1]


array([-0.00760554, -0.01886755, -0.00862955, ..., -0.00883273,
       -0.05742338, -0.02446945])